export const APP_NAME = 'Finance Quest';
export const SAVE_VERSION = 3;

export const SLOT_ORDER = [
  { key: 'head', label: 'Elmo', description: 'Planejamento e visão de risco.' },
  { key: 'shoulders', label: 'Ombreiras', description: 'Proteção e reserva.' },
  { key: 'chest', label: 'Armadura', description: 'Consistência financeira.' },
  { key: 'hands', label: 'Luvas', description: 'Execução e registro.' },
  { key: 'neck', label: 'Amuleto', description: 'Leitura de mercado.' },
  { key: 'mainHand', label: 'Arma principal', description: 'Estratégia de aporte.' },
  { key: 'offHand', label: 'Tomo', description: 'Comparação e estudo.' },
  { key: 'feet', label: 'Botas', description: 'Mobilidade entre classes de ativos.' },
  { key: 'ring1', label: 'Anel I', accepts: ['ring'], description: 'Hábito.' },
  { key: 'ring2', label: 'Anel II', accepts: ['ring'], description: 'Revisão.' },
];

export const EMPTY_EQUIPMENT = SLOT_ORDER.reduce((equipment, slot) => {
  equipment[slot.key] = null;
  return equipment;
}, {});

export const RARITY_META = {
  comum: {
    label: 'Comum',
    color: '#9FB3C8',
    aura: '#6B7F95',
    minAmount: 0,
    baseWeight: 58,
    xpMultiplier: 1,
    itemDropMultiplier: 1,
  },
  raro: {
    label: 'Raro',
    color: '#62D6A6',
    aura: '#2DD4BF',
    minAmount: 350,
    baseWeight: 28,
    xpMultiplier: 1.04,
    itemDropMultiplier: 1.03,
  },
  epico: {
    label: 'Épico',
    color: '#5AC8FA',
    aura: '#38BDF8',
    minAmount: 900,
    baseWeight: 12,
    xpMultiplier: 1.08,
    itemDropMultiplier: 1.06,
  },
  lendario: {
    label: 'Lendário',
    color: '#F6C453',
    aura: '#F59E0B',
    minAmount: 1800,
    baseWeight: 4,
    xpMultiplier: 1.14,
    itemDropMultiplier: 1.1,
  },
  artefato: {
    label: 'Artefato',
    color: '#FF7A6B',
    aura: '#F43F5E',
    minAmount: 4000,
    baseWeight: 1,
    xpMultiplier: 1.22,
    itemDropMultiplier: 1.16,
  },
};

export const CHARACTER_RACES = [
  {
    key: 'guardiao',
    label: 'Guardião da Reserva',
    bonus: 'Começa com foco em segurança, liquidez e proteção.',
  },
  {
    key: 'arcanista',
    label: 'Arcanista dos Índices',
    bonus: 'Valoriza leitura de dados, diversificação e consistência.',
  },
  {
    key: 'mercador',
    label: 'Mercador Estratégico',
    bonus: 'Compara oportunidades, custos e prazos antes de agir.',
  },
];

export const CHARACTER_CLASSES = [
  {
    key: 'renda-fixa',
    label: 'Sentinela da Renda Fixa',
    bonus: 'Prioriza reserva, previsibilidade e disciplina.',
  },
  {
    key: 'diversificacao',
    label: 'Explorador Global',
    bonus: 'Busca classes diferentes com risco consciente.',
  },
  {
    key: 'longo-prazo',
    label: 'Cronomante do Longo Prazo',
    bonus: 'Usa tempo, juros compostos e revisão periódica.',
  },
];

export const INVESTMENT_CATEGORIES = [
  { key: 'renda-fixa', label: 'Renda fixa', icon: 'shield-half-full' },
  { key: 'renda-variavel', label: 'Renda variável', icon: 'sword-cross' },
  { key: 'fundos', label: 'Fundos e ETFs', icon: 'chart-donut' },
  { key: 'global', label: 'Global', icon: 'earth' },
  { key: 'longo-prazo', label: 'Longo prazo', icon: 'timer-sand-complete' },
];

export const INVESTMENT_TYPES = {
  'tesouro-selic': {
    title: 'Tesouro Selic',
    category: 'renda-fixa',
    keywords: ['tesouro selic', 'selic', 'tesouro direto', 'título público', 'titulo publico'],
    baseXp: 90,
    power: 18,
    icon: 'shield-check',
    learning:
      'Boa referência para reserva de emergência por combinar liquidez, baixo risco e acompanhamento simples.',
  },
  'tesouro-ipca': {
    title: 'Tesouro IPCA+',
    category: 'renda-fixa',
    keywords: ['tesouro ipca', 'ipca+', 'ntn-b', 'inflação', 'inflacao'],
    baseXp: 110,
    power: 22,
    icon: 'fire-shield',
    learning:
      'Ajuda a pensar em proteção contra inflação quando o objetivo tem prazo mais longo.',
  },
  cdb: {
    title: 'CDB',
    category: 'renda-fixa',
    keywords: ['cdb', 'certificado de depósito', 'certificado de deposito', 'banco emissor'],
    baseXp: 95,
    power: 19,
    icon: 'bank-check',
    learning:
      'Permite comparar rentabilidade, prazo, liquidez, emissor e cobertura do FGC.',
  },
  'lci-lca': {
    title: 'LCI/LCA',
    category: 'renda-fixa',
    keywords: ['lci', 'lca', 'agronegócio', 'agronegocio', 'imobiliário', 'imobiliario'],
    baseXp: 100,
    power: 20,
    icon: 'leaf-circle',
    learning:
      'Reforça a análise de prazo, isenção de IR, liquidez e garantia para pessoa física.',
  },
  fii: {
    title: 'Fundo Imobiliário',
    category: 'renda-variavel',
    keywords: ['fii', 'fundo imobiliário', 'fundo imobiliario', 'hglg11', 'mxrf11', 'dividend yield'],
    baseXp: 120,
    power: 25,
    icon: 'home-city-outline',
    learning:
      'Estimula leitura de vacância, contratos, recorrência de rendimentos e diversificação.',
  },
  acao: {
    title: 'Ação',
    category: 'renda-variavel',
    keywords: ['ação', 'acao', 'ações', 'acoes', 'b3', 'ticker', 'petrobras', 'vale3', 'itub4'],
    baseXp: 130,
    power: 28,
    icon: 'finance',
    learning:
      'Exige leitura de negócio, risco, governança, preço e horizonte de investimento.',
  },
  etf: {
    title: 'ETF',
    category: 'fundos',
    keywords: ['etf', 'ivvb11', 'bova11', 'smal11', 'índice', 'indice', 's&p', 'sp500'],
    baseXp: 125,
    power: 27,
    icon: 'chart-box-outline',
    learning:
      'Facilita exposição diversificada e comparação com índices de referência.',
  },
  bdr: {
    title: 'BDR',
    category: 'global',
    keywords: ['bdr', 'recibo', 'apple', 'google', 'nvidia', 'mercado global'],
    baseXp: 135,
    power: 29,
    icon: 'earth-arrow-right',
    learning:
      'Conecta o usuário a empresas globais e à variação cambial com responsabilidade.',
  },
  'fundo-previdencia': {
    title: 'Fundo de Previdência',
    category: 'longo-prazo',
    keywords: ['previdência', 'previdencia', 'pgbl', 'vgbl', 'aposentadoria'],
    baseXp: 115,
    power: 24,
    icon: 'clock-star-four-points-outline',
    learning:
      'Ajuda a organizar horizonte, tributação, taxa de administração e disciplina.',
  },
};

export const SET_BONUSES = {
  'Ordem da Reserva Estável': {
    category: 'renda-fixa',
    affectedTypes: ['tesouro-selic', 'tesouro-ipca', 'cdb', 'lci-lca'],
    lore: 'Conjunto defensivo para reserva, liquidez e renda fixa consciente.',
    bonuses: [
      { pieces: 2, label: '+10% XP em renda fixa', xpMultiplier: 1.1, itemDropMultiplier: 1.03, power: 12 },
      { pieces: 4, label: '+18% XP e +8% chance de drop', xpMultiplier: 1.18, itemDropMultiplier: 1.08, power: 18 },
    ],
  },
  'Conclave da Diversificação': {
    category: 'fundos',
    affectedTypes: ['etf', 'bdr', 'acao', 'fii'],
    lore: 'Conjunto para comparar riscos, setores e moedas diferentes.',
    bonuses: [
      { pieces: 2, label: '+8% XP em ativos diversificados', xpMultiplier: 1.08, itemDropMultiplier: 1.04, power: 10 },
      { pieces: 4, label: '+16% XP e +10% chance de drop', xpMultiplier: 1.16, itemDropMultiplier: 1.1, power: 16 },
    ],
  },
  'Círculo do Longo Prazo': {
    category: 'longo-prazo',
    affectedTypes: ['fundo-previdencia', 'tesouro-ipca', 'etf'],
    lore: 'Conjunto de constância para objetivos que dependem de tempo.',
    bonuses: [
      { pieces: 2, label: '+9% XP em longo prazo', xpMultiplier: 1.09, itemDropMultiplier: 1.03, power: 11 },
      { pieces: 4, label: '+15% XP e +20 de poder', xpMultiplier: 1.15, itemDropMultiplier: 1.08, power: 20 },
    ],
  },
};

export const ITEM_LIBRARY = [
  {
    id: 'elmo-reserva-inicial',
    name: 'Elmo da Reserva Inicial',
    slot: 'head',
    type: 'tesouro-selic',
    category: 'renda-fixa',
    rarity: 'comum',
    setName: 'Ordem da Reserva Estável',
    requiredAmount: 100,
    power: 14,
    xpMultiplier: 1.02,
    itemDropMultiplier: 1,
    icon: 'shield-sun-outline',
    bonusLabel: '+2% XP em registros',
    flavor: 'Primeira peça de proteção contra decisões impulsivas.',
    lore: 'Reserva de emergência é o escudo básico de qualquer jornada financeira.',
  },
  {
    id: 'ombreiras-liquidez-diaria',
    name: 'Ombreiras da Liquidez Diária',
    slot: 'shoulders',
    type: 'tesouro-selic',
    category: 'renda-fixa',
    rarity: 'raro',
    setName: 'Ordem da Reserva Estável',
    requiredAmount: 450,
    power: 22,
    xpMultiplier: 1.04,
    itemDropMultiplier: 1.02,
    icon: 'shield-half-full',
    bonusLabel: '+4% XP e +2% drop',
    flavor: 'Mantém recursos acessíveis quando a vida exige resposta rápida.',
    lore: 'Liquidez evita vender investimentos ruins no pior momento.',
  },
  {
    id: 'armadura-cdb-comparado',
    name: 'Armadura do CDB Comparado',
    slot: 'chest',
    type: 'cdb',
    category: 'renda-fixa',
    rarity: 'epico',
    setName: 'Ordem da Reserva Estável',
    requiredAmount: 900,
    power: 32,
    xpMultiplier: 1.08,
    itemDropMultiplier: 1.04,
    icon: 'bank-check',
    bonusLabel: '+8% XP e +4% drop',
    flavor: 'Compara taxa, prazo, liquidez e proteção do FGC.',
    lore: 'Nem todo CDB serve ao mesmo objetivo; contexto importa.',
  },
  {
    id: 'luvas-lci-lca-isenta',
    name: 'Luvas da Isenção LCI/LCA',
    slot: 'hands',
    type: 'lci-lca',
    category: 'renda-fixa',
    rarity: 'lendario',
    setName: 'Ordem da Reserva Estável',
    requiredAmount: 1800,
    power: 42,
    xpMultiplier: 1.14,
    itemDropMultiplier: 1.08,
    icon: 'leaf-circle',
    bonusLabel: '+14% XP e +8% drop',
    flavor: 'Transforma comparação líquida em disciplina de análise.',
    lore: 'Isenção de IR não dispensa análise de prazo, risco e liquidez.',
  },
  {
    id: 'tomo-ipca-horizonte',
    name: 'Tomo IPCA+ do Horizonte',
    slot: 'offHand',
    type: 'tesouro-ipca',
    category: 'renda-fixa',
    rarity: 'artefato',
    setName: 'Círculo do Longo Prazo',
    requiredAmount: 4200,
    power: 58,
    xpMultiplier: 1.2,
    itemDropMultiplier: 1.12,
    icon: 'book-lock-open-outline',
    bonusLabel: '+20% XP e +12% drop',
    flavor: 'Brilha quando o objetivo precisa atravessar muitos anos.',
    lore: 'O IPCA+ pede entendimento de prazo e marcação a mercado.',
  },
  {
    id: 'amuleto-fiis-recorrencia',
    name: 'Amuleto dos FIIs Recorrentes',
    slot: 'neck',
    type: 'fii',
    category: 'renda-variavel',
    rarity: 'raro',
    setName: 'Conclave da Diversificação',
    requiredAmount: 500,
    power: 24,
    xpMultiplier: 1.04,
    itemDropMultiplier: 1.03,
    icon: 'home-city-outline',
    bonusLabel: '+4% XP e +3% drop',
    flavor: 'Revela vacância, contratos e recorrência de rendimentos.',
    lore: 'FIIs combinam renda, risco de mercado e risco imobiliário.',
  },
  {
    id: 'lamina-acao-fundamentalista',
    name: 'Lâmina da Ação Fundamentalista',
    slot: 'mainHand',
    type: 'acao',
    category: 'renda-variavel',
    rarity: 'epico',
    setName: 'Conclave da Diversificação',
    requiredAmount: 1000,
    power: 36,
    xpMultiplier: 1.09,
    itemDropMultiplier: 1.05,
    icon: 'sword-cross',
    bonusLabel: '+9% XP e +5% drop',
    flavor: 'Corta ruído de curto prazo para enxergar valor e risco.',
    lore: 'Ações exigem leitura de negócio, preço, governança e horizonte.',
  },
  {
    id: 'botas-etf-indices',
    name: 'Botas dos Índices Amplos',
    slot: 'feet',
    type: 'etf',
    category: 'fundos',
    rarity: 'epico',
    setName: 'Conclave da Diversificação',
    requiredAmount: 950,
    power: 34,
    xpMultiplier: 1.08,
    itemDropMultiplier: 1.05,
    icon: 'chart-box-outline',
    bonusLabel: '+8% XP e +5% drop',
    flavor: 'Atravessa mercados inteiros sem depender de um único ativo.',
    lore: 'Índices ajudam a comparar carteira própria com referências amplas.',
  },
  {
    id: 'bussola-bdr-global',
    name: 'Bússola Global dos BDRs',
    slot: 'offHand',
    type: 'bdr',
    category: 'global',
    rarity: 'lendario',
    setName: 'Conclave da Diversificação',
    requiredAmount: 2200,
    power: 46,
    xpMultiplier: 1.15,
    itemDropMultiplier: 1.09,
    icon: 'earth-arrow-right',
    bonusLabel: '+15% XP e +9% drop',
    flavor: 'Aponta para empresas globais sem ignorar o câmbio.',
    lore: 'Ativos globais diversificam, mas adicionam variação cambial.',
  },
  {
    id: 'anel-previdencia-constante',
    name: 'Anel da Previdência Constante',
    slot: 'ring',
    type: 'fundo-previdencia',
    category: 'longo-prazo',
    rarity: 'lendario',
    setName: 'Círculo do Longo Prazo',
    requiredAmount: 2000,
    power: 44,
    xpMultiplier: 1.14,
    itemDropMultiplier: 1.08,
    icon: 'ring',
    bonusLabel: '+14% XP e +8% drop',
    flavor: 'Aumenta de poder quando o usuário mantém constância.',
    lore: 'Previdência exige atenção a tributação, taxas, portabilidade e horizonte.',
  },
  {
    id: 'anel-juros-compostos',
    name: 'Anel dos Juros Compostos',
    slot: 'ring',
    type: 'fundo-previdencia',
    category: 'longo-prazo',
    rarity: 'artefato',
    setName: 'Círculo do Longo Prazo',
    requiredAmount: 5000,
    power: 62,
    xpMultiplier: 1.24,
    itemDropMultiplier: 1.14,
    icon: 'creation',
    bonusLabel: '+24% XP e +14% drop',
    flavor: 'Quanto mais tempo equipado, mais forte a disciplina parece.',
    lore: 'Tempo e consistência são grandes aliados dos juros compostos.',
  },
  {
    id: 'capa-aporte-manual',
    name: 'Capa do Registro Manual',
    slot: 'shoulders',
    type: 'aporte-manual',
    category: 'fundos',
    rarity: 'comum',
    setName: 'Conclave da Diversificação',
    requiredAmount: 50,
    power: 12,
    xpMultiplier: 1.01,
    itemDropMultiplier: 1,
    icon: 'file-document-edit-outline',
    bonusLabel: '+1% XP em registros',
    flavor: 'Mesmo sem comprovante perfeito, a jornada continua.',
    lore: 'Registrar com consistência é melhor do que abandonar o acompanhamento.',
  },
];

export const ITEM_REWARD_TRACKS = Object.keys(INVESTMENT_TYPES).reduce((tracks, typeKey) => {
  tracks[typeKey] = ITEM_LIBRARY.filter((item) => item.type === typeKey || item.type === 'aporte-manual').map((item) => item.id);
  return tracks;
}, {});

export const QUESTS = [
  {
    id: 'primeiro-aporte',
    title: 'Primeiro Aporte Arcano',
    description: 'Registre o primeiro investimento e receba um drop inicial.',
    target: 1,
    metric: 'historyCount',
    reward: 'Libera o inventário e a primeira peça.',
  },
  {
    id: 'reserva-emergencia',
    title: 'Muralha da Reserva',
    description: 'Registre pelo menos R$ 1.000,00 em renda fixa.',
    target: 1000,
    metric: 'fixedIncomeAmount',
    reward: 'Aumenta o domínio da Ordem da Reserva Estável.',
  },
  {
    id: 'diversificacao-inicial',
    title: 'Mapa das Três Rotas',
    description: 'Registre ativos de pelo menos três categorias.',
    target: 3,
    metric: 'categoryCount',
    reward: 'Mostra a amplitude da carteira.',
  },
  {
    id: 'poder-250',
    title: 'Maestria do Portfólio',
    description: 'Alcance 250 de poder somando equipamentos e histórico.',
    target: 250,
    metric: 'power',
    reward: 'Desbloqueia status de aventureiro avançado.',
  },
];

export const ACHIEVEMENTS = [
  {
    id: 'primeiro-drop',
    title: 'Primeiro Drop',
    description: 'Recebeu o primeiro item da jornada.',
    metric: 'inventoryCount',
    target: 1,
  },
  {
    id: 'quatro-pecas',
    title: 'Quatro Peças, Uma Ordem',
    description: 'Equipou quatro itens do mesmo conjunto.',
    metric: 'largestSet',
    target: 4,
  },
  {
    id: 'cinco-rotas',
    title: 'Cinco Rotas Financeiras',
    description: 'Registrou cinco tipos de investimento diferentes.',
    metric: 'typeCount',
    target: 5,
  },
  {
    id: 'artefato-lendario',
    title: 'Eco de Artefato',
    description: 'Conquistou pelo menos um item de raridade artefato.',
    metric: 'artifactCount',
    target: 1,
  },
];

export const DEFAULT_GAME_STATE = {
  meta: {
    saveVersion: SAVE_VERSION,
    characterCreated: false,
    createdAt: null,
    updatedAt: null,
    exportCount: 0,
    duplicateDrops: 0,
  },
  player: {
    name: '',
    race: CHARACTER_RACES[0].key,
    classKey: CHARACTER_CLASSES[0].key,
  },
  wallet: {
    coins: 120,
    crystals: 0,
  },
  inventory: [],
  equipment: { ...EMPTY_EQUIPMENT },
  history: [],
};

export function characterAvatarKey(player = DEFAULT_GAME_STATE.player) {
  return `${player.race || 'guardiao'}-${player.classKey || 'renda-fixa'}`;
}
